// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbAlcaldes
    {
        public string Alca_Imagen { get; set; }
        public string Muni_Codigo { get; set; }
        public int Part_Id { get; set; }
        public int Alca_UsuarioCreacion { get; set; }
        public DateTime Alca_FechaCreacion { get; set; }
        public int? Alca_UsuarioModifica { get; set; }
        public DateTime? Alca_FechaModifica { get; set; }
        public bool? Alca_Estado { get; set; }
        public int Alca_Id { get; set; }

        public virtual tbVotantes Alca { get; set; }
        public virtual tbUsuarios Alca_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Alca_UsuarioModificaNavigation { get; set; }
        public virtual tbMunicipios Muni_CodigoNavigation { get; set; }
        public virtual tbPartidos Part { get; set; }
    }
}