// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        public string Dept_Codigo { get; set; }
        public string Dept_Descripcion { get; set; }
        public int Dept_UsuarioCreacion { get; set; }
        public DateTime Dept_FechaCreacion { get; set; }
        public int? Dept_UsuarioModifica { get; set; }
        public DateTime? Dept_FechaModifica { get; set; }

        public virtual tbUsuarios Dept_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Dept_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}