// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbEmpleados
    {
        public int Empl_UsuarioCreacion { get; set; }
        public DateTime Empl_FechaCreacion { get; set; }
        public int? Empl_UsuarioModifica { get; set; }
        public DateTime? Empl_FechaModifica { get; set; }
        public bool? Empl_Estado { get; set; }
        public int Part_Id { get; set; }
        public int Carg_Id { get; set; }
        public int Empl_Id { get; set; }
        public int Sede_Id { get; set; }
        public int Mesa_Id { get; set; }

        public virtual tbCargos Carg { get; set; }
        public virtual tbVotantes Empl { get; set; }
        public virtual tbUsuarios Empl_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Empl_UsuarioModificaNavigation { get; set; }
        public virtual tbPartidos Part { get; set; }
    }
}