// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbEmpleadosPorMesaElectoral
    {
        public int EPME_Id { get; set; }
        public int MePS_Id { get; set; }
        public int Empl_Id { get; set; }
    }
}