// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbVotantes = new HashSet<tbVotantes>();
        }

        public int Esta_Id { get; set; }
        public string Esta_Descripcion { get; set; }
        public int Esta_UsuarioCreacion { get; set; }
        public DateTime Esta_FechaCreacion { get; set; }
        public int? Esta_UsuarioModifica { get; set; }
        public DateTime? Esta_FechaModifica { get; set; }

        public virtual tbUsuarios Esta_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Esta_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbVotantes> tbVotantes { get; set; }
    }
}