// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbMesasPorSedes
    {
        public tbMesasPorSedes()
        {
            tbVotantes = new HashSet<tbVotantes>();
        }

        public int MePS_Id { get; set; }
        public int Mesa_Id { get; set; }
        public int Sede_Id { get; set; }

        public virtual ICollection<tbVotantes> tbVotantes { get; set; }
    }
}