// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbAlcaldes = new HashSet<tbAlcaldes>();
            tbVotantes = new HashSet<tbVotantes>();
        }

        public string Muni_Codigo { get; set; }
        public string Muni_Descripcion { get; set; }
        public string Dept_Codigo { get; set; }
        public int Muni_UsuarioCreacion { get; set; }
        public DateTime Muni_FechaCreacion { get; set; }
        public int? Muni_UsuarioModifica { get; set; }
        public DateTime? Muni_FechaModifica { get; set; }
        public int Sede_Id { get; set; }
        public string Sede_Descripcion { get; set; }
        public virtual tbDepartamentos Dept_CodigoNavigation { get; set; }
        public virtual tbUsuarios Muni_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Muni_UsuarioModificaNavigation { get; set; }
        public virtual ICollection<tbAlcaldes> tbAlcaldes { get; set; }
        public virtual ICollection<tbVotantes> tbVotantes { get; set; }
    }
}