// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int Paro_Id { get; set; }
        public int Rol_Id { get; set; }
        public int Pant_Id { get; set; }
        public string Pant_Descripcion { get; set; }
        public string Pant_IconoBootstrap { get; set; }

        public string Pant_Controlador { get; set; }
        public int Esqu_Id { get; set; }
        public string Esqu_Descripcion { get; set; }

        public virtual tbPantallas Pant { get; set; }
        public virtual tbRoles Rol { get; set; }
    }
}