// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbSedes
    {
        public int Sede_Id { get; set; }
        public string Sede_Descripcion { get; set; }
        public string Muni_Codigo { get; set; }
        public int Sede_UsuarioCreacion { get; set; }
        public DateTime Sede_FechaCreacion { get; set; }
        public int? Sede_UsuarioModifica { get; set; }
        public DateTime? Sede_FechaModifica { get; set; }
        public bool? Sede_Estado { get; set; }

        public virtual tbUsuarios Sede_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Sede_UsuarioModificaNavigation { get; set; }
    }
}