// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbVotosPorMesas
    {
        public int VoMe_Id { get; set; }
        public int MePS_Id { get; set; }
        public int VoMe_CandidatoId { get; set; }
        public bool VoMe_EsPresidente { get; set; }

        [NotMapped]
        public string Vota_Nombre { get; internal set; }


        public string Nombre { get; set; }
        public string Apellidos { get; set; }

        public string Cargo { get; set; }

        public int CandidatoId { get; set; }
        public int TotalVotos { get; set; }

    }
}