// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbVotantes
    {
        public int Vota_Id { get; set; }
        public string Vota_Nombre { get; set; }
        public string Vota_Apellidos { get; set; }
        public string Vota_DNI { get; set; }
        public bool Vota_YaVoto { get; set; }
        public string Muni_Codigo { get; set; }
        public int Esta_Id { get; set; }
        public int Vota_UsuarioCreacion { get; set; }
        public DateTime Vota_FechaCreacion { get; set; }
        public int? Vota_UsuarioModifica { get; set; }
        public DateTime? Vota_FechaModifica { get; set; }
        public int Sede_Id { get; set; }
        public int Mesa_Id { get; set; }
        public int MePS_Id { get; set; }

        public virtual tbEstadosCiviles Esta { get; set; }
        public virtual tbMesasPorSedes MePS { get; set; }
        public virtual tbMunicipios Muni_CodigoNavigation { get; set; }
        public virtual tbUsuarios Vota_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Vota_UsuarioModificaNavigation { get; set; }
        public virtual tbAlcaldes tbAlcaldes { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
        public virtual tbPresidentes tbPresidentes { get; set; }
    }
}