// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbVotosPorMesas
    {
        public int VoMe_Id { get; set; }
        public int MePS_Id { get; set; }
        public int VoMe_CandidatoId { get; set; }
        public bool VoMe_EsPresidente { get; set; }

        [NotMapped]
        public string Vota_Nombre { get; internal set; }


        public string Nombre { get; set; }
        public string Apellidos { get; set; }

        public string Cargo { get; set; }

        public int CandidatoId { get; set; }
        public int TotalVotos { get; set; }


        public string NombrePresidente { get; set; }
        public string ApellidoPresidente { get; set; }
        public string CargoPresidente { get; set; }
        public int CandidatoIdPresidente { get; set; }
        public int TotalVotosPresidentes { get; set; }


        public string NombreAlcalde { get; set; }
        public string ApellidoAlcalde { get; set; }
        public string CargoAlcalde { get; set; }
        public int CandidatoIdAlcalde { get; set; }
        public int TotalVotosAlcalde { get; set; }

        public bool Vota_YaVoto { get; set; }
    }
}