// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Votaciones.Entities.Entities
{
    public partial class tbVotosPorMesas
    {
        public int VoMe_Id { get; set; }
        public int MePS_Id { get; set; }
        public int VoMe_CandidatoId { get; set; }
        public bool VoMe_EsPresidente { get; set; }
    }
}