// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Sistema_Votaciones.Entities.Entities;

#nullable disable

namespace Sistema_Votaciones.DataAcess.Context
{
    public partial class BD_SistemavotacionesContext : DbContext
    {
        public BD_SistemavotacionesContext()
        {
        }

        public BD_SistemavotacionesContext(DbContextOptions<BD_SistemavotacionesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbAlcaldes> tbAlcaldes { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEmpleadosPorMesaElectoral> tbEmpleadosPorMesaElectoral { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbMesas> tbMesas { get; set; }
        public virtual DbSet<tbMesasPorSedes> tbMesasPorSedes { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual DbSet<tbPartidos> tbPartidos { get; set; }
        public virtual DbSet<tbPresidentes> tbPresidentes { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbSedes> tbSedes { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbVotantes> tbVotantes { get; set; }
        public virtual DbSet<tbVotosPorMesas> tbVotosPorMesas { get; set; }
        public virtual DbSet<tbVotosPorMesas_Bitacora> tbVotosPorMesas_Bitacora { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tbAlcaldes>(entity =>
            {
                entity.HasKey(e => e.Alca_Id)
                    .HasName("PK__tbAlcald__B257DDA00DAD4FCB");

                entity.ToTable("tbAlcaldes", "Vota");

                entity.Property(e => e.Alca_Id).ValueGeneratedNever();

                entity.Property(e => e.Alca_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Alca_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Alca_FechaModifica).HasColumnType("datetime");

                entity.Property(e => e.Alca_Imagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.Muni_Codigo)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.HasOne(d => d.Alca)
                    .WithOne(p => p.tbAlcaldes)
                    .HasForeignKey<tbAlcaldes>(d => d.Alca_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Alca_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbAlcaldesAlca_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Alca_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbAlcaldes_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Alca_UsuarioModificaNavigation)
                    .WithMany(p => p.tbAlcaldesAlca_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Alca_UsuarioModifica)
                    .HasConstraintName("FK_tbAlcaldes_tbUsuarios_Usua_UsuarioModifica");

                entity.HasOne(d => d.Muni_CodigoNavigation)
                    .WithMany(p => p.tbAlcaldes)
                    .HasForeignKey(d => d.Muni_Codigo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbAlcaldes_Muni_Id");

                entity.HasOne(d => d.Part)
                    .WithMany(p => p.tbAlcaldes)
                    .HasForeignKey(d => d.Part_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbAlcaldes_Part_Id");
            });

            modelBuilder.Entity<tbCargos>(entity =>
            {
                entity.HasKey(e => e.Carg_Id)
                    .HasName("PK__tbCargos__B0D859FAFD7CB388");

                entity.ToTable("tbCargos", "Gral");

                entity.Property(e => e.Carg_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Carg_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Carg_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Carg_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Carg_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbCargosCarg_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Carg_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbCargos_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Carg_UsuarioModificaNavigation)
                    .WithMany(p => p.tbCargosCarg_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Carg_UsuarioModifica)
                    .HasConstraintName("FK_tbCargos_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbDepartamentos>(entity =>
            {
                entity.HasKey(e => e.Dept_Codigo)
                    .HasName("PK__tbDepart__02786912B8B5767D");

                entity.ToTable("tbDepartamentos", "Gral");

                entity.Property(e => e.Dept_Codigo)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Dept_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Dept_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Dept_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Dept_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbDepartamentosDept_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Dept_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbDepartamentos_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Dept_UsuarioModificaNavigation)
                    .WithMany(p => p.tbDepartamentosDept_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Dept_UsuarioModifica)
                    .HasConstraintName("FK_tbDepartamentos_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbEmpleados>(entity =>
            {
                entity.HasKey(e => e.Empl_Id)
                    .HasName("PK__tbEmplea__2EB12E86C2285D54");

                entity.ToTable("tbEmpleados", "Gral");

                entity.Property(e => e.Empl_Id).ValueGeneratedNever();

                entity.Property(e => e.Empl_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Empl_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Empl_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Carg)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Carg_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbEmpleados_Carg_Id");

                entity.HasOne(d => d.Empl)
                    .WithOne(p => p.tbEmpleados)
                    .HasForeignKey<tbEmpleados>(d => d.Empl_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbAlcaldes_tbVotantes_Empl_Id");

                entity.HasOne(d => d.Empl_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbEmpleadosEmpl_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Empl_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbEmpleados_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Empl_UsuarioModificaNavigation)
                    .WithMany(p => p.tbEmpleadosEmpl_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Empl_UsuarioModifica)
                    .HasConstraintName("FK_tbEmpleados_tbUsuarios_Usua_UsuarioModifica");

                entity.HasOne(d => d.Part)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Part_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbEmpleados_Part_Id");
            });

            modelBuilder.Entity<tbEmpleadosPorMesaElectoral>(entity =>
            {
                entity.HasKey(e => e.EPME_Id)
                    .HasName("PK__tbEmplea__936DC22ED3E2A181");

                entity.ToTable("tbEmpleadosPorMesaElectoral", "Vota");
            });

            modelBuilder.Entity<tbEstadosCiviles>(entity =>
            {
                entity.HasKey(e => e.Esta_Id)
                    .HasName("PK__tbEstado__D52AE7B8074DAB11");

                entity.ToTable("tbEstadosCiviles", "Gral");

                entity.Property(e => e.Esta_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Esta_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Esta_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Esta_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsta_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Esta_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbEstadosCiviles_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Esta_UsuarioModificaNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsta_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Esta_UsuarioModifica)
                    .HasConstraintName("FK_tbEstadosCiviles_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbMesas>(entity =>
            {
                entity.HasKey(e => e.Mesa_Id)
                    .HasName("PK__tbMesas__019353A689ECE4A1");

                entity.ToTable("tbMesas", "Gral");

                entity.Property(e => e.Mesa_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Mesa_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Mesa_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Mesa_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbMesasMesa_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Mesa_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbMesas_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Mesa_UsuarioModificaNavigation)
                    .WithMany(p => p.tbMesasMesa_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Mesa_UsuarioModifica)
                    .HasConstraintName("FK_tbMesas_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbMesasPorSedes>(entity =>
            {
                entity.HasKey(e => e.MePS_Id)
                    .HasName("PK__tbMesasP__BB012434977C85F8");

                entity.ToTable("tbMesasPorSedes", "Vota");
            });

            modelBuilder.Entity<tbMunicipios>(entity =>
            {
                entity.HasKey(e => e.Muni_Codigo)
                    .HasName("PK__tbMunici__289AC128BE0A94DE");

                entity.ToTable("tbMunicipios", "Gral");

                entity.Property(e => e.Muni_Codigo)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Dept_Codigo)
                    .IsRequired()
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Muni_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Muni_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Muni_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Dept_CodigoNavigation)
                    .WithMany(p => p.tbMunicipios)
                    .HasForeignKey(d => d.Dept_Codigo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbMunicipios_Dept_Codigo");

                entity.HasOne(d => d.Muni_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbMunicipiosMuni_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Muni_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbMunicipios_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Muni_UsuarioModificaNavigation)
                    .WithMany(p => p.tbMunicipiosMuni_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Muni_UsuarioModifica)
                    .HasConstraintName("FK_tbMunicipios_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbPantallas>(entity =>
            {
                entity.HasKey(e => e.Pant_Id)
                    .HasName("PK__tbPantal__CF98C932716B1A01");

                entity.ToTable("tbPantallas", "Acce");

                entity.Property(e => e.Pant_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pant_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Pant_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Pant_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Pant_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbPantallasPant_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Pant_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbPantallas_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Pant_UsuarioModificaNavigation)
                    .WithMany(p => p.tbPantallasPant_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Pant_UsuarioModifica)
                    .HasConstraintName("FK_tbPantallas_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbPantallasPorRoles>(entity =>
            {
                entity.HasKey(e => e.Paro_Id)
                    .HasName("PK__tbPantal__53819DE9F92644C4");

                entity.ToTable("tbPantallasPorRoles", "Acce");

                entity.HasOne(d => d.Pant)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Pant_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbPantallasPorRoles_Pant_Id");

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Rol_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbPantallasPor_Roles_Id");
            });

            modelBuilder.Entity<tbPartidos>(entity =>
            {
                entity.HasKey(e => e.Part_Id)
                    .HasName("PK__tbPartid__14CFF410429C2D54");

                entity.ToTable("tbPartidos", "Vota");

                entity.Property(e => e.Part_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Part_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Part_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Part_FechaModifica).HasColumnType("datetime");

                entity.Property(e => e.Part_Imagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.HasOne(d => d.Part_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbPartidosPart_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Part_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbPartidos_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Part_UsuarioModificaNavigation)
                    .WithMany(p => p.tbPartidosPart_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Part_UsuarioModifica)
                    .HasConstraintName("FK_tbPartidos_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbPresidentes>(entity =>
            {
                entity.HasKey(e => e.Pres_Id)
                    .HasName("PK__tbPresid__84FF9A16A022EE79");

                entity.ToTable("tbPresidentes", "Vota");

                entity.Property(e => e.Pres_Id).ValueGeneratedNever();

                entity.Property(e => e.Pres_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Pres_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Pres_FechaModifica).HasColumnType("datetime");

                entity.Property(e => e.Pres_Imagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.HasOne(d => d.Part)
                    .WithMany(p => p.tbPresidentes)
                    .HasForeignKey(d => d.Part_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbPartidos_Part_Id");

                entity.HasOne(d => d.Pres)
                    .WithOne(p => p.tbPresidentes)
                    .HasForeignKey<tbPresidentes>(d => d.Pres_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbVotantes_Pres_Id");

                entity.HasOne(d => d.Pres_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbPresidentesPres_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Pres_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbPresidentes_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Pres_UsuarioModificaNavigation)
                    .WithMany(p => p.tbPresidentesPres_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Pres_UsuarioModifica)
                    .HasConstraintName("FK_tbPresidentes_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.Rol_Id)
                    .HasName("PK__tbRoles__795EBD49467819D5");

                entity.ToTable("tbRoles", "Acce");

                entity.Property(e => e.Rol_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Rol_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Rol_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Rol_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Rol_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbRolesRol_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Rol_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbRoles_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Rol_UsuarioModificaNavigation)
                    .WithMany(p => p.tbRolesRol_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Rol_UsuarioModifica)
                    .HasConstraintName("FK_tbRoles_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbSedes>(entity =>
            {
                entity.HasKey(e => e.Sede_Id)
                    .HasName("PK__tbSedes__BB300E1487AFA8A2");

                entity.ToTable("tbSedes", "Gral");

                entity.Property(e => e.Muni_Codigo)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Sede_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Sede_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Sede_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Sede_FechaModifica).HasColumnType("datetime");

                entity.HasOne(d => d.Sede_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbSedesSede_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Sede_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbSedes_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Sede_UsuarioModificaNavigation)
                    .WithMany(p => p.tbSedesSede_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Sede_UsuarioModifica)
                    .HasConstraintName("FK_tbSedes_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usua_Id)
                    .HasName("PK__tbUsuari__E863C8EE2E2D9E68");

                entity.ToTable("tbUsuarios", "Acce");

                entity.HasIndex(e => e.Usua_Usuario, "UQ__tbUsuari__9ED44AB40B10FC17")
                    .IsUnique();

                entity.Property(e => e.Usua_Activo)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Usua_Contra)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_FechaModifica).HasColumnType("datetime");

                entity.Property(e => e.Usua_Usuario)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbUsuarios)
                    .HasForeignKey(d => d.Rol_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Usua_UsuarioCreacionNavigation)
                    .WithMany(p => p.InverseUsua_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Usua_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Usua_UsuarioModificaNavigation)
                    .WithMany(p => p.InverseUsua_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Usua_UsuarioModifica);
            });

            modelBuilder.Entity<tbVotantes>(entity =>
            {
                entity.HasKey(e => e.Vota_Id)
                    .HasName("PK__tbVotant__1ED6B8F1C184457C");

                entity.ToTable("tbVotantes", "Gral");

                entity.Property(e => e.Muni_Codigo)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Vota_Apellidos)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Vota_DNI)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Vota_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Vota_FechaModifica).HasColumnType("datetime");

                entity.Property(e => e.Vota_Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Esta)
                    .WithMany(p => p.tbVotantes)
                    .HasForeignKey(d => d.Esta_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbVotantes_Esta_Id");

                entity.HasOne(d => d.MePS)
                    .WithMany(p => p.tbVotantes)
                    .HasForeignKey(d => d.MePS_Id)
                    .HasConstraintName("FK_tbVotantes_MePS_Id");

                entity.HasOne(d => d.Muni_CodigoNavigation)
                    .WithMany(p => p.tbVotantes)
                    .HasForeignKey(d => d.Muni_Codigo)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbVotantes_Muni_Id");

                entity.HasOne(d => d.Vota_UsuarioCreacionNavigation)
                    .WithMany(p => p.tbVotantesVota_UsuarioCreacionNavigation)
                    .HasForeignKey(d => d.Vota_UsuarioCreacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbVotantes_tbUsuarios_Usua_UsuarioCreacion");

                entity.HasOne(d => d.Vota_UsuarioModificaNavigation)
                    .WithMany(p => p.tbVotantesVota_UsuarioModificaNavigation)
                    .HasForeignKey(d => d.Vota_UsuarioModifica)
                    .HasConstraintName("FK_tbVotantes_tbUsuarios_Usua_UsuarioModifica");
            });

            modelBuilder.Entity<tbVotosPorMesas>(entity =>
            {
                entity.HasKey(e => e.VoMe_Id)
                    .HasName("PK__tbVotosP__2F9BEC813AFBCCC8");

                entity.ToTable("tbVotosPorMesas", "Vota");
            });

            modelBuilder.Entity<tbVotosPorMesas_Bitacora>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("tbVotosPorMesas_Bitacora", "Vota");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}